// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btctcturggemmhicnrmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0Y3RjdHVyZ2dlbW1oaWNucm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNzE2MjksImV4cCI6MjA1MDg0NzYyOX0.Q1VBtz3oqQoCu5esYzoZysnK-S319z5Cw7__rIRKEXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);